os: linux
language: csharp
dotnet: 2.1.4
mono: none
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1

before_install:
  - chmod +x ./build.sh
script:
  - ./build.sh
