version: 1.0.{build}

pull_requests:

  do_not_increment_build_number: true

environment:

  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

  DOTNET_CLI_TELEMETRY_OPTOUT: true

nuget:

  disable_publish_on_pr: true

build_script:

- ps: .\build.ps1

test: off

artifacts:

- path: .\artifacts\*.nupkg

  name: NuGet

- path: .\test-results\*.xml

  name: Xunit

deploy: off

notifications:

- provider: Email

  to:

  - zabrowarnyrafal@gmail.com

  on_build_success: true

  on_build_failure: true

  on_build_status_changed: false
