version: '{build}'
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
  - develop
  - /release\/*/
  - /hotfix\/*/
skip_tags: true
shallow_clone: true
environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  VERSION_INFO_SEMVER: null
  VERSION_INFO: null
nuget:
  project_feed: true
  disable_publish_on_pr: true
init:
before_build:
- ps: >-
    $version_info_json = (gitversion /l console /output json);
    $version_info = ($version_info_json | ConvertFrom-Json)
    
    $env:VERSION_INFO = $version_info;
    
    $env:VERSION_INFO_SEMVER = $version_info.SemVer;
    Update-AppveyorBuild -Version "$env:VERSION_INFO_SEMVER-$env:APPVEYOR_BUILD_NUMBER";
    Write-Host "version_info_json = " $version_info_json
    Write-Host "Set VERSION_INFO_SEMVER = " $env:VERSION_INFO_SEMVER;
    
    Write-Host "Set APPVEYOR_BUILD_VERSION = " $env:APPVEYOR_BUILD_VERSION;
build_script:
- ps: .\build.ps1
test: off
artifacts:
- path: .\artifacts\*.nupkg
  name: NuGet
- path: .\test-results\*.xml
  name: Xunit
deploy: off
